### ISSUE TITLE
Arc segments API is difficult to understand to the point of being unusable

### ISSUE THREAD

**Issue by johansen** [jonobr1/two.js#206] opened 2016-10-28 21:02 UTC
Try as I might, I can't comprehend how to use the arc segment drawing API. Consider the following demo:

```
<!DOCTYPE html>
<html>
<head>
    <title>Arc Segment Demo</title>
    <script src="./two.js"></script>

    <script>
        function ready(fn) {
            if (document.readyState != 'loading'){
                fn();
            } else {
                document.addEventListener('DOMContentLoaded', fn);
            }
        }

        ready(function(){
            var elem = document.getElementById('draw-shapes');
            var two = new Two({ width: 500, height: 500 }).appendTo(elem);

            var ir = 0;
            var or = 100;
            var sa = Math.PI;
            var ea = Math.PI;

            var arc;
            function updateArc() {
                if(arc) {
                    two.remove(arc);
                }

                arc = two.makeArcSegment(
                    250, 250,
                    ir, or,
                    sa, ea
                );
                arc.stroke = "#001f3f";
                arc.linewidth = 1.5;

                two.update();
            }

            updateArc();

            function pctToRads(pct) {
                var proportion = parseFloat(pct) / 100;
                return proportion * 2 * Math.PI;
            }

            document.querySelector("#startAngle").addEventListener("input", function(evt){
                sa = pctToRads(evt.target.value);
                console.log("startAngle: " + sa);
                updateArc();
            });
            document.querySelector("#endAngle").addEventListener("input", function(evt){
                ea = pctToRads(evt.target.value);
                console.log("endAngle: " + ea);
                updateArc();
            });
        });

    </script>
</head>
<body>
    <div id="draw-shapes"></div>
    <div id="controls">
        <input type="range" id="startAngle"/>
        <input type="range" id="endAngle"/>
    </div>
</body>
</html>
```

By adjusting the sliders, the start angle and end angle range between 0 and 2*PI. But the behavior of the arc segment that gets drawn is incomprehensible. The segment seems to rotate around the center in a way I can't account for, and thus the `makeArcSegment` function is useless to me.

What I would have expected is for the `sa` and `ea` parameters to be absolute. So if I give a starting angle of 50 degrees and an ending angle of 60 degrees, I would see an arc drawn between 50 and 60 degrees from some fixed axis. But this isn't what seems to happen.

I must be misunderstanding something, but at very least the documentation doesn't account sufficiently for the behavior of this function for me to be able to make use of it.

**Comment by jonobr1** [comment] 2016-10-28 21:58
Thanks for raising this @johansen! This sounds like a bug in the library. I'll take a look at this over the weekend and get back to you with something that works in an absolute space. It should totally work how you're describing.

**Comment by larrybotha** [comment] 2016-10-28 23:55
Take a look here: http://codepen.io/larrybotha/pen/amredV?editors=0010

I converted radians to degrees in the console to make it easier to understand what's going on.

If you set `sa` to 0deg, and shift `ea`, `ea` rotates anti-clockwise at the expected degree value.

What is interesting is if you then set the `sa` to 90deg, `sa` rotates clockwise, and `ea` is offset 90deg from `sa` clockwise. If you set `ea` to 90deg, it rotates anti-clockwise to a 0deg arc.

I'm not sure if this is the intended behaviour by @jonobr1, but that should give you a better idea of what's going on at least!

I made a clock with draggable hands via arcSegments, it may assist in further exploration for you: http://codepen.io/larrybotha/pen/VKmOqQ

**Comment by jonobr1** [comment] 2016-10-31 20:12
Hey @johansen,

I've updated Two.js' [`dev` branch](https://github.com/jonobr1/two.js/tree/dev) with a fix for this. It includes new properties on the `Two.ArcSegment`:
+ `Two.ArcSegment.startAngle`,
+ `Two.ArcSegment.endAngle`,
+ `Two.ArcSegment.innerRadius`
+ `Two.ArcSegment.outerRadius`

You can see an example of that here: http://codepen.io/jonobr1/full/VKovWP/

**Closed by jonobr1** 2016-10-31 20:12 UTC
Labels: bug, enhancement

**Comment by johansen** [comment] 2016-10-31 20:13
That looks perfect. Just the behavior I had been expecting.

**Comment by dumptyd** [comment] 2018-01-25 12:59
Hi, this might be really easy but I can't figure out how to do this. I want to draw an arc using `makeArcSegment` anticlockwise, like HTML5 canvas's `arc` function. Is there a way to do this with two.js?

**Comment by larrybotha** [comment] 2018-01-25 15:16
@dumptyd on the second input in the following demo set `max=100` and `min=-100` and give the input a bash - it draws the arc in both directions:

https://codepen.io/jonobr1/pen/VKovWP?editors=1010

**Comment by jonobr1** [comment] 2018-01-25 17:43
Following up on @larrybotha's answer, if you make the `arc.endAngle` less than the `arc.startAngle` then it should go in the opposite direction.
